# fly.toml app configuration file generated for school-project on 2024-02-29T15:36:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'school-project'
primary_region = 'ams'
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[[vm]]
  size = 'shared-cpu-1x'
